List<Map<String, dynamic>> products = [
  {
    'image': 'assets/images/products/aocado.png',
    'price': 23.23,
    'name': 'Avocado',
    'unit': '2.0 lbs',
  },
  {
    'image': 'assets/images/products/grapes.png',
    'price': 12.44,
    'name': 'Grapes',
    'unit': '5.0 lbs',
  },
  {
    'image': 'assets/images/products/green-fresh-broccoli.png',
    'price': 67.88,
    'name': 'Broccoli',
    'unit': '1 kg',
  },
  {
    'image': 'assets/images/products/peach.png',
    'price': 43.42,
    'name': 'Peach',
    'unit': 'dozen',
  },
  {
    'image': 'assets/images/products/pineapple-pieces.png',
    'price': 12.67,
    'name': 'Pineapple Pieces',
    'unit': '1.50 lbs',
  },
  {
    'image': 'assets/images/products/pomegranate.png',
    'price': 90.32,
    'name': 'Pomegranate',
    'unit': '1.50 lbs',
  },
  {
    'image': 'assets/images/products/apple.png',
    'price': 25.50,
    'name': 'Apple',
    'unit': '1.0 kg',
  },
  {
    'image': 'assets/images/products/banana.png',
    'price': 18.75,
    'name': 'Banana',
    'unit': '1 dozen',
  },
  {
    'image': 'assets/images/products/mango.png',
    'price': 55.20,
    'name': 'Mango',
    'unit': '2.0 kg',
  },
  {
    'image': 'assets/images/products/orange.png',
    'price': 30.00,
    'name': 'Orange',
    'unit': '1.5 kg',
  },
  {
    'image': 'assets/images/products/kiwi.png',
    'price': 40.25,
    'name': 'Kiwi',
    'unit': '0.5 kg',
  },
  {
    'image': 'assets/images/products/strawberry.png',
    'price': 75.99,
    'name': 'Strawberry',
    'unit': '1.0 box',
  },
  {
    'image': 'assets/images/products/watermelon.png',
    'price': 100.00,
    'name': 'Watermelon',
    'unit': '1 piece',
  },
  {
    'image': 'assets/images/products/blueberries.png',
    'price': 60.40,
    'name': 'Blueberries',
    'unit': '250 g',
  },
  {
    'image': 'assets/images/products/lettuce.png',
    'price': 20.10,
    'name': 'Lettuce',
    'unit': '1 head',
  },
  {
    'image': 'assets/images/products/tomato.png',
    'price': 15.00,
    'name': 'Tomato',
    'unit': '1.0 kg',
  },
];
